# Generated by Django 5.0.1 on 2024-11-06 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivajobsApp', '0002_alter_estudiante_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
