# Generated by Django 5.0.1 on 2024-11-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivajobsApp', '0003_alter_estudiante_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleador',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nombre',
        ),
    ]
