# Generated by Django 5.0.1 on 2024-11-07 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivajobsApp', '0004_remove_empleador_nombre_remove_estudiante_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleador',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleador',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
