# Generated by Django 5.0.1 on 2024-11-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivajobsApp', '0006_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleador',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleador',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
