# Generated by Django 5.0.1 on 2024-11-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivajobsApp', '0007_empleador_is_active_empleador_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='habilidades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
