# Generated by Django 5.0.1 on 2024-11-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivajobsApp', '0008_estudiante_descripcion_estudiante_habilidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='ofertas',
            field=models.ManyToManyField(blank=True, related_name='postulantes', to='cultivajobsApp.oferta'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='descripcion',
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='habilidades',
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
