# Generated by Django 5.0.1 on 2024-11-13 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivajobsApp', '0009_estudiante_ofertas_alter_estudiante_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='empleador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='cultivajobsApp.empleador'),
            preserve_default=False,
        ),
    ]
