# Generated by Django 5.0.1 on 2024-11-13 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivajobsApp', '0010_oferta_empleador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='empleador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='cultivajobsApp.empleador'),
        ),
    ]
