# Generated by Django 5.0.1 on 2024-11-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivajobsApp', '0011_alter_oferta_empleador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='empleador',
        ),
        migrations.AddField(
            model_name='oferta',
            name='empleadores',
            field=models.ManyToManyField(blank=True, related_name='ofertas', to='cultivajobsApp.empleador'),
        ),
    ]
