# Generated by Django 5.0.1 on 2024-11-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivajobsApp', '0012_remove_oferta_empleador_oferta_empleadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
