# Generated by Django 5.0.1 on 2024-11-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivajobsApp', '0013_estudiante_direccion_estudiante_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='categoria',
            field=models.CharField(choices=[('CR', 'Comida Rápida'), ('RT', 'Retail'), ('SP', 'Supermercado'), ('LM', 'Logística y Mensajería'), ('AT', 'Atención al Cliente')], default='CR', max_length=2),
        ),
    ]
